const commonItems = [
  {
    type: "box",
    name: "common_box",
    tier: "common",
    buy: 2329.45,
    alias: ["cb", "commonbox", "cbox", "combox", "common_b", "c_b", "c", "common"],
  },
  {
    type: "melee",
    name: "baseball_bat",
    tier: "common",
    damage: { min: 5, max: 8 },
    cooldown: 1474,
    buy: 1301.3,
    sell: 464.75,
    alias: ["bat", "bb", "baseballbat", "b_bat"],
  },
  {
    type: "ammo",
    name: "2mm_bullet",
    tier: "common",
    used_for: ["kolibri"],
    sell: 858,
    alias: ["2mm", "2mmbullet", "2mm_b", "2mm_bul"],
  },
  {
    type: "firearm",
    name: "kolibri",
    tier: "common",
    ammo: "2mm_bullet",
    damage: { min: 8, max: 16 },
    cooldown: 2335,
    sell: 2676,
    alias: ["kol", "koli", "kolib"],
  },
  {
    type: "money",
    name: "piggy_bank",
    tier: "common",
    money: { min: 400, max: 650 },
    value: 525,
    alias: ["pb", "piggybank", "pbank", "piggy", "p_b", "p"],
  },
  {
    type: "melee",
    name: "bowling_ball",
    tier: "common",
    damage: { min: 3, max: 7 },
    cooldown: 1134,
    buy: 1001.0,
    sell: 357.5,
    alias: ["bowlingball", "bb", "b_ball", "ball", "bowl"],
  },
  {
    type: "melee",
    name: "butter_knife",
    tier: "common",
    damage: { min: 2, max: 6 },
    cooldown: 907,
    buy: 800.8,
    sell: 286.0,
    alias: ["butterknife", "bk", "b_knife", "knife", "butter", "but", "butt"],
  },
  {
    type: "melee",
    name: "golf_club",
    tier: "common",
    damage: { min: 5, max: 8 },
    cooldown: 1474,
    buy: 1301.3,
    sell: 464.75,
    alias: ["golfclub", "gc", "g_club", "club", "golf"],
  },
  {
    type: "melee",
    name: "frying_pan",
    tier: "common",
    damage: { min: 3, max: 6 },
    cooldown: 1020,
    buy: 900.9,
    sell: 321.75,
    alias: ["fryingpan", "fp", "f_pan", "pan", "fry"],
  },
  {
    type: "melee",
    name: "hammer",
    tier: "common",
    damage: { min: 5, max: 8 },
    cooldown: 1474,
    buy: 1301.3,
    sell: 464.75,
    alias: ["ham", "hammer"],
  },
  {
    type: "melee",
    name: "rock",
    tier: "common",
    damage: { min: 2, max: 5 },
    cooldown: 793,
    buy: 700.7,
    sell: 250.25,
    alias: ["stone", "rock", "rck", "rk"],
  },
  {
    type: "melee",
    name: "shank",
    tier: "common",
    damage: { min: 3, max: 7 },
    cooldown: 1134,
    buy: 1001.0,
    sell: 357.5,
    alias: ["shiv", "shank", "stab", "sh"],
  },
  {
    type: "ammo",
    name: "wooden_arrow",
    tier: "common",
    used_for: ["wooden_bow"],
    sell: 1394.25,
    alias: ["arrow", "woodenarrow", "w_arrow", "woodarrow", "arr"],
  },
  {
    type: "melee",
    name: "wrench",
    tier: "common",
    damage: { min: 3, max: 6 },
    cooldown: 1020,
    buy: 900.9,
    sell: 321.75,
    alias: ["wrench", "wr", "wren"],
  },
  {
    type: "heal",
    name: "bandage",
    tier: "common",
    heal: { min: 1, max: 3 },
    cooldown: 333,
    buy: 560.0,
    sell: 200.0,
    alias: ["band", "bandage", "bndg", "bnd"],
  },
  {
    type: "melee",
    name: "scissors",
    tier: "common",
    damage: { min: 4, max: 7 },
    cooldown: 1247,
    buy: 1101.1,
    sell: 393.25,
    alias: ["scissors", "scissor", "sc", "scis", "scisors", "scisr", "scisrz"],
  },
  {
    type: "melee",
    name: "shovel",
    tier: "common",
    damage: { min: 6, max: 12 },
    cooldown: 2041,
    buy: 1801.8,
    sell: 643.5,
    alias: ["shovel", "shov", "shvl", "shv", "spade"],
  },
];

module.exports = commonItems;
