const epicItems = [
  {
    type: "box",
    name: "epic_box",
    tier: "epic",
    sell: 37230.51,
    value: 5000.0,
    alias: ["eb", "epicbox", "epbox", "epic_b", "epic"],
  },
  {
    type: "firearm",
    name: "awp",
    tier: "epic",
    ammo: ".308_winchester_bullet",
    damage: { min: 65, max: 80 },
    cooldown: 10197,
    sell: 29101.5,
    alias: ["avm"],
  },
  {
    type: "firearm",
    name: "barrett_m82",
    tier: "epic",
    ammo: ".50_bmg_bullet",
    damage: { min: 75, max: 85 },
    cooldown: 11120,
    sell: 32112.0,
    alias: ["barrett", "m82", "barrettm82", "barr"],
  },
  {
    type: "firearm",
    name: "ar-50",
    tier: "epic",
    ammo: ".50_bmg_bullet",
    damage: { min: 72, max: 82 },
    cooldown: 10703,
    sell: 30907.8,
    alias: ["ar50", "ar_50", "ar"],
  },
  {
    type: "firearm",
    name: ".44_magnum",
    tier: "epic",
    ammo: ".44_magnum_bullet",
    damage: { min: 55, max: 75 },
    cooldown: 9035,
    sell: 26091.0,
    alias: ["44", "magnum", "44mag", "44magnum", "44_magnum"],
  },
  {
    type: "firearm",
    name: "desert_eagle",
    tier: "epic",
    ammo: ".50ae_bullet",
    damage: { min: 60, max: 80 },
    cooldown: 9730,
    sell: 28098.0,
    alias: ["deagle", "desert", "eagle"],
  },
  {
    type: "firearm",
    name: "henry_45-70",
    tier: "epic",
    ammo: "45-70_bullet",
    damage: { min: 62, max: 78 },
    cooldown: 9730,
    sell: 28098.0,
    alias: ["henry", "4570", "henry_4570"],
  },
  {
    type: "money",
    name: "treasure_chest",
    tier: "epic",
    money: { min: 24500, max: 42424 },
    value: 33462.0,
    alias: ["treasure", "treasurechest", "tchest", "chest"],
  },
];

module.exports = epicItems;
