const rareItems = [
  {
    type: "box",
    name: "rare_box",
    tier: "rare",
    buy: 8587.17,
    alias: ["rb", "rarebox", "rbox", "rare_b", "r_b", "r", "rare"],
  },
  {
    type: "melee",
    name: "fire_axe",
    tier: "rare",
    damage: { min: 20, max: 25 },
    cooldown: 4374,
    buy: 3861.0,
    sell: 2252.25,
    alias: ["fireaxe", "faxe", "fa", "axe", "fire"],
  },
  {
    type: "melee",
    name: "machete",
    tier: "rare",
    damage: { min: 23, max: 28 },
    cooldown: 4957,
    buy: 4375.8,
    sell: 2552.55,
    alias: ["mach", "mache"],
  },
  {
    type: "melee",
    name: "karambit",
    tier: "rare",
    damage: { min: 20, max: 26 },
    cooldown: 4471,
    buy: 3946.8,
    sell: 2302.3,
    alias: ["karam", "kar", "kara"],
  },
  {
    type: "melee",
    name: "shurikens",
    tier: "rare",
    damage: { min: 16, max: 21 },
    cooldown: 3596,
    buy: 3174.6,
    sell: 1851.85,
    alias: ["shuriken", "shuri", "shur"],
  },
  {
    type: "melee",
    name: "tomahawk",
    tier: "rare",
    damage: { min: 23, max: 28 },
    cooldown: 4957,
    buy: 4375.8,
    sell: 2552.55,
    alias: ["tom", "hawk", "toma"],
  },
  {
    type: "heal",
    name: "first_aid_kit",
    tier: "rare",
    heal: { min: 25, max: 30 },
    cooldown: 3927,
    buy: 6600.0,
    sell: 3850.0,
    alias: ["fak", "firstaid", "firstaidkit", "first_aid", "firstaid_kit"],
  },
  {
    type: "melee",
    name: "cleaver",
    tier: "rare",
    damage: { min: 16, max: 21 },
    cooldown: 3596,
    buy: 3174.6,
    sell: 1851.85,
    alias: ["cleave", "cleav", "cle"],
  },
  {
    type: "melee",
    name: "rapier",
    tier: "rare",
    damage: { min: 22, max: 26 },
    cooldown: 4665,
    buy: 4118.4,
    sell: 2402.4,
    alias: ["rap"],
  },
  {
    type: "ammo",
    name: "5.56_bullet",
    tier: "rare",
    used_for: ["famas", "m4_carbine"],
    sell: 4191.68,
    alias: ["556", "556bullet", "5_56", "5.56", "556_bullet"],
  },
  {
    type: "ammo",
    name: "7.62_bullet",
    tier: "rare",
    used_for: ["ak-47"],
    sell: 4004.0,
    alias: ["762", "762bullet", "7_62", "7.62", "762_bullet"],
  },
  {
    type: "ammo",
    name: "12_gauge_bullet",
    tier: "rare",
    used_for: ["remington_870"],
    sell: 4004.0,
    alias: ["12", "12g", "12gauge", "12g_bullet", "12gaugebullet"],
  },
  {
    type: "firearm",
    name: "glock-17",
    tier: "rare",
    ammo: "9mm_bullet",
    damage: { min: 21, max: 35 },
    cooldown: 4670,
    sell: 8741.6,
    alias: ["17", "glock", "glock17", "g17"],
  },
  {
    type: "firearm",
    name: "mac-10",
    tier: "rare",
    ammo: ".45_acp_bullet",
    damage: { min: 15, max: 40 },
    cooldown: 4587,
    sell: 8585.5,
    alias: ["mac10", "mac", "m10", "mac_10"],
  },
  {
    type: "firearm",
    name: "thompson",
    tier: "rare",
    ammo: ".45_acp_bullet",
    damage: { min: 15, max: 45 },
    cooldown: 5024,
    sell: 9366.0,
    alias: ["tommy", "tommygun", "thomp", "thom"],
  },
  {
    type: "firearm",
    name: "vector",
    tier: "rare",
    ammo: ".45_acp_bullet",
    damage: { min: 23, max: 34 },
    cooldown: 4753,
    sell: 8897.7,
    alias: ["kriss", "krissvector", "vec", "vctr"],
  },
  {
    type: "firearm",
    name: "m1911",
    tier: "rare",
    ammo: ".45_acp_bullet",
    damage: { min: 23, max: 38 },
    cooldown: 5087,
    sell: 9522.1,
    alias: ["1911", "colt1911", "colt", "m-1911"],
  },
  {
    type: "melee",
    name: "kunai",
    tier: "rare",
    damage: { min: 18, max: 23 },
    cooldown: 3985,
    buy: 3517.8,
    sell: 2052.05,
    alias: ["kunai", "ku", "knai"],
  },
  {
    type: "money",
    name: "moneybag",
    tier: "rare",
    money: { min: 2300, max: 4200 },
    value: 3250.0,
    alias: ["bag", "m_bag", "money_bag"],
  },
];

module.exports = rareItems;
