const rareItems = [
  {
    type: "box",
    name: "rare_box",
    tier: "rare",
    buy: 8587.17,
    alias: ["rb", "rarebox", "rbox", "rare_b", "r_b", "r"],
  },
  {
    type: "melee",
    name: "fire_axe",
    tier: "rare",
    damage: { min: 20, max: 25 },
    cooldown: 4374,
    buy: 3861.0,
    sell: 2252.25,
    alias: ["fireaxe", "faxe", "fa", "axe", "fire"],
  },
  {
    type: "melee",
    name: "machete",
    tier: "rare",
    damage: { min: 23, max: 28 },
    cooldown: 4957,
    buy: 4375.8,
    sell: 2552.55,
    alias: ["machete", "mach", "mache"],
  },
  {
    type: "melee",
    name: "karambit",
    tier: "rare",
    damage: { min: 20, max: 26 },
    cooldown: 4471,
    buy: 3946.8,
    sell: 2302.3,
    alias: ["karambit", "karam", "kar", "kara"],
  },
  {
    type: "melee",
    name: "shurikens",
    tier: "rare",
    damage: { min: 16, max: 21 },
    cooldown: 3596,
    buy: 3174.6,
    sell: 1851.85,
    alias: ["shuriken", "shurikens", "shuri", "shur"],
  },
  {
    type: "melee",
    name: "tomahawk",
    tier: "rare",
    damage: { min: 23, max: 28 },
    cooldown: 4957,
    buy: 4375.8,
    sell: 2552.55,
    alias: ["tomahawk", "tom", "hawk", "toma"],
  },
  {
    type: "heal",
    name: "first_aid_kit",
    tier: "rare",
    heal: { min: 25, max: 30 },
    cooldown: 3927,
    buy: 6600.0,
    sell: 3850.0,
    alias: ["fak", "firstaid", "firstaidkit", "first_aid", "firstaid_kit"],
  },
  {
    type: "melee",
    name: "cleaver",
    tier: "rare",
    damage: { min: 16, max: 21 },
    cooldown: 3596,
    buy: 3174.6,
    sell: 1851.85,
    alias: ["cleaver", "cleave", "cleav", "cle"],
  },
  {
    type: "ammo",
    name: "5.56_bullet",
    tier: "rare",
    used_for: ["famas", "m4_carbine"],
    sell: 4191.68,
    alias: ["556", "556bullet", "5_56", "5.56", "556_bullet"],
  },
  {
    type: "ammo",
    name: "7.62_bullet",
    tier: "rare",
    used_for: ["ak-47"],
    sell: 4004.0,
    alias: ["762", "762bullet", "7_62", "7.62", "762_bullet"],
  },
  {
    type: "ammo",
    name: "12_gauge_bullet",
    tier: "rare",
    used_for: ["remington_870"],
    sell: 4004.0,
    alias: ["12", "12g", "12gauge", "12g_bullet", "12gaugebullet"],
  },
  {
    type: "firearm",
    name: "glock-17",
    tier: "rare",
    ammo: "9mm_bullet",
    damage: { min: 21, max: 35 },
    cooldown: 4670,
    sell: 8741.6,
    alias: ["17", "glock", "glock17", "g17", "glock-17"],
  },
  {
    type: "money",
    name: "moneybag",
    tier: "rare",
    money: { min: 2300, max: 4200 },
    value: 3250.0,
    alias: ["bag", "moneybag", "m_bag", "money_bag"],
  },
];

module.exports = rareItems;
