const ultraRareItems = [
  {
    type: "box",
    name: "ultra_rare_box",
    tier: "ultra_rare",
    buy: 15111.59,
    alias: ["urb", "urbox", "ultrararebox", "ultra_box", "ur", "ultra", "ultrarare"],
  },
  {
    type: "melee",
    name: "katana",
    tier: "ultra_rare",
    damage: { min: 40, max: 45 },
    cooldown: 7573,
    buy: 6685.25,
    sell: 4862.0,
    alias: ["katana", "kat", "kata"],
  },
  {
    type: "firearm",
    name: "mp5",
    tier: "ultra_rare",
    ammo: "9mm_bullet",
    damage: { min: 25, max: 55 },
    cooldown: 6116,
    sell: 14272.0,
    alias: ["mp5", "mp"],
  },
  {
    type: "firearm",
    name: "famas",
    tier: "ultra_rare",
    ammo: "5.56_bullet",
    damage: { min: 35, max: 40 },
    cooldown: 5733,
    sell: 13380.0,
    alias: ["famas", "fam", "fr"],
  },
  {
    type: "firearm",
    name: "m4_carbine",
    tier: "ultra_rare",
    ammo: "5.56_bullet",
    damage: { min: 40, max: 48 },
    cooldown: 6727,
    sell: 15699.2,
    alias: ["m4", "m4carbine", "m4_c", "ct"],
  },
  {
    type: "firearm",
    name: "ak-47",
    tier: "ultra_rare",
    ammo: "7.62_bullet",
    damage: { min: 45, max: 52 },
    cooldown: 7615,
    sell: 17304.8,
    alias: ["ak", "ak47", "ak_47", "47", "t"],
  },
  {
    type: "firearm",
    name: "remington_870",
    tier: "ultra_rare",
    ammo: "12_gauge_bullet",
    damage: { min: 10, max: 70 },
    cooldown: 6116,
    sell: 14272.0,
    alias: ["remington", "rem870", "r870", "remington870", "870", "rem", "reming"],
  },
  {
    type: "firearm",
    name: "m1_garand",
    tier: "ultra_rare",
    ammo: ".30-06_bullet",
    damage: { min: 48, max: 56 },
    cooldown: 7950,
    sell: 18553.6,
    alias: ["m1", "garand", "m1garand", "m1g"],
  },
  {
    type: "money",
    name: "safe",
    tier: "ultra_rare",
    money: { min: 4999, max: 16050 },
    value: 10524.5,
    alias: ["safe", "saf", "sf"],
  },
  {
    type: "ammo",
    name: ".308_winchester_bullet",
    tier: "ultra_rare",
    used_for: ["awp"],
    sell: 8294.0,
    alias: ["308", "winchester", "308win", "308winchester", "308_bullet"],
  },
  {
    type: "ammo",
    name: ".50_bmg_bullet",
    tier: "ultra_rare",
    used_for: ["ar-50", "barrett_m82"],
    sell: 8980.4,
    alias: ["50", "bmg", "50bmg", "50_bmg", "bmg_bullet"],
  },
  {
    type: "ammo",
    name: ".44_magnum_bullet",
    tier: "ultra_rare",
    used_for: [".44_magnum"],
    sell: 7436.0,
    alias: ["44", "magnum", "44mag", "44magnum", "44_magnum"],
  },
  {
    type: "ammo",
    name: ".30-06_bullet",
    tier: "ultra_rare",
    used_for: ["m1_garand"],
    sell: 5948.8,
    alias: ["30-06", "3006", "30_06", "30", "06", "30-06_bullet"],
  },
];

module.exports = ultraRareItems;
