// Uncommon rarity items
const uncommonItems = [
  {
    name: "uncommon_box",
    type: "box",
    tier: "uncommon",
    buy: 4319.88,
    alias: ["ub", "uncommonbox", "ubox", "unbox", "uncommon_b", "u_b", "un"],
  },
  {
    type: "melee",
    name: "spear",
    tier: "uncommon",
    damage: { min: 16, max: 22 },
    cooldown: 4001,
    buy: 3532.1,
    sell: 1630.2,
    alias: ["spear", "sp"],
  },
  {
    type: "melee",
    name: "scythe",
    tier: "uncommon",
    damage: { min: 17, max: 20 },
    cooldown: 3896,
    buy: 3439.15,
    sell: 1587.3,
    alias: ["scythe", "sc", "scy"],
  },
  {
    type: "ammo",
    name: "9mm_bullet",
    tier: "uncommon",
    used_for: ["glock-17", "mp5"],
    sell: 2917.2,
    alias: ["9mm", "9mmbullet", "9mm_b", "9mm_bul", "9"],
  },
  {
    type: "money",
    name: "wallet",
    tier: "uncommon",
    money: { min: 1200, max: 1900 },
    value: 1550.0,
    alias: ["wallet", "wal", "w"],
  },
  {
    type: "heal",
    name: "antibiotics",
    tier: "uncommon",
    heal: { min: 9, max: 13 },
    cooldown: 1701,
    buy: 2860.0,
    sell: 1320.0,
    alias: ["abx", "antibiotic", "antibiotics"],
  },
  {
    type: "melee",
    name: "crowbar",
    tier: "uncommon",
    damage: { min: 11, max: 16 },
    cooldown: 2843,
    buy: 2509.65,
    sell: 1158.3,
    alias: ["crowbar", "cb", "crow", "bar"],
  },
  {
    type: "melee",
    name: "pickaxe",
    tier: "uncommon",
    damage: { min: 13, max: 18 },
    cooldown: 3264,
    buy: 2881.45,
    sell: 1329.9,
    alias: ["pickaxe", "pick", "axe", "pax", "pa"],
  },
  {
    type: "melee",
    name: "sledgehammer",
    tier: "uncommon",
    damage: { min: 13, max: 18 },
    cooldown: 3264,
    buy: 2881.45,
    sell: 1329.9,
    alias: ["sledge", "sledgehammer", "shammer", "sled"],
  },
  {
    type: "firearm",
    name: "wooden_bow",
    tier: "uncommon",
    ammo: ["wooden_arrow"],
    damage: { min: 17, max: 22 },
    cooldown: 3523,
    sell: 5218.2,
    alias: ["woodenbow", "wbow", "bow", "woodbow", "wb"],
  },
  {
    type: "heal",
    name: "painkillers",
    tier: "uncommon",
    heal: { min: 7, max: 11 },
    cooldown: 1392,
    buy: 2340.0,
    sell: 1080.0,
    alias: ["pk", "painkiller", "painkillers", "pain", "killers", "pkx"],
  },
];

module.exports = uncommonItems;
